### ISSUE TITLE
Could we have a more generic `etc`  modules to put files in any path?

### ISSUE THREAD

**Issue by Vonfry** [nix-community/robotnix#214]
The `etc` module is implemented though `robotnix/etcfiles` sources. However, some apps use config files under `/sdcard/` directly which is other than app resouces and etc.

**Comment by Atemu** [comment]
That won't work as /sdcard is on the userdata partition. etcfiles are put into the system image's /etc.

Everything robotnix does concerns system partition currently.

**Comment by Atemu** [comment]
Declarative config of userdata things is something I'd *love* to have aswell but that'd be its own separate project; similar to NixOS and home-manager.

The most robotnix could do is bake running that other project into the system image so that you wouldn't have to install it imperatively.
